//go:build linux

package doctor

import (
	"os"
	"path/filepath"
	"testing"
)

func TestCheckResolvConfRouting(t *testing.T) {
	t.Run("correct symlink", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "resolv.conf")
		os.Symlink(resolvedStubPath, path)

		res := checkResolvConfRouting(path)
		if res.Status != Pass {
			t.Errorf("expected Pass for correct symlink, got %v: %s", res.Status, res.Message)
		}
	})

	t.Run("wrong symlink", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "resolv.conf")
		os.Symlink("/run/NetworkManager/resolv.conf", path)

		// Write content so ReadFile works through the symlink — but it won't
		// resolve, so it falls through to reading as a file.
		// For this test, create the file directly.
		os.Remove(path)
		os.WriteFile(path, []byte("# Generated by NetworkManager\nnameserver 192.168.1.1\n"), 0644)

		res := checkResolvConfRouting(path)
		if res.Status != Fail {
			t.Errorf("expected Fail for wrong content, got %v: %s", res.Status, res.Message)
		}
	})

	t.Run("contains 127.0.0.53", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "resolv.conf")
		os.WriteFile(path, []byte("nameserver 127.0.0.53\nsearch home\n"), 0644)

		res := checkResolvConfRouting(path)
		if res.Status != Pass {
			t.Errorf("expected Pass for file containing 127.0.0.53, got %v: %s", res.Status, res.Message)
		}
	})

	t.Run("tailscale managed", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "resolv.conf")
		content := "# resolv.conf(5) file generated by tailscale\nnameserver 100.100.100.100\n"
		os.WriteFile(path, []byte(content), 0644)

		res := checkResolvConfRouting(path)
		if res.Status != Fail {
			t.Errorf("expected Fail, got %v", res.Status)
		}
		if got := res.Message; got != "resolv.conf is managed by Tailscale, bypassing systemd-resolved" {
			t.Errorf("unexpected message: %s", got)
		}
	})

	t.Run("missing file", func(t *testing.T) {
		res := checkResolvConfRouting("/nonexistent/resolv.conf")
		if res.Status != Fail {
			t.Errorf("expected Fail for missing file, got %v", res.Status)
		}
	})
}

func TestContainsNameserver(t *testing.T) {
	tests := []struct {
		name    string
		content string
		addr    string
		want    bool
	}{
		{"found", "nameserver 127.0.0.53\n", "127.0.0.53", true},
		{"not found", "nameserver 8.8.8.8\n", "127.0.0.53", false},
		{"multiple", "nameserver 8.8.8.8\nnameserver 127.0.0.53\n", "127.0.0.53", true},
		{"commented", "# nameserver 127.0.0.53\n", "127.0.0.53", false},
		{"empty", "", "127.0.0.53", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := containsNameserver([]byte(tt.content), tt.addr); got != tt.want {
				t.Errorf("containsNameserver(%q, %q) = %v, want %v", tt.content, tt.addr, got, tt.want)
			}
		})
	}
}

func TestIdentifyResolvConfManager(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{"tailscale", "# generated by tailscale\nnameserver 100.100.100.100\n", "Tailscale"},
		{"networkmanager", "# Generated by NetworkManager\nnameserver 192.168.1.1\n", "NetworkManager"},
		{"resolvconf", "# Generated by resolvconf\nnameserver 8.8.8.8\n", "resolvconf"},
		{"unknown", "nameserver 8.8.8.8\n", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, "resolv.conf")
			os.WriteFile(path, []byte(tt.content), 0644)

			if got := identifyResolvConfManager(path, []byte(tt.content)); got != tt.want {
				t.Errorf("identifyResolvConfManager() = %q, want %q", got, tt.want)
			}
		})
	}

	t.Run("networkmanager symlink", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "resolv.conf")
		os.Symlink("/run/NetworkManager/resolv.conf", path)

		got := identifyResolvConfManager(path, []byte("nameserver 192.168.1.1\n"))
		if got != "NetworkManager" {
			t.Errorf("expected NetworkManager for NM symlink, got %q", got)
		}
	})
}

func TestFindStubListenerDisabled(t *testing.T) {
	// This tests hasStubListenerDisabled since findStubListenerDisabled
	// reads from fixed system paths.

	t.Run("disabled in resolve section", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.conf")
		os.WriteFile(path, []byte("[Resolve]\nDNSStubListener=no\n"), 0644)

		if !hasStubListenerDisabled(path) {
			t.Error("expected true for DNSStubListener=no")
		}
	})

	t.Run("enabled", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.conf")
		os.WriteFile(path, []byte("[Resolve]\nDNSStubListener=yes\n"), 0644)

		if hasStubListenerDisabled(path) {
			t.Error("expected false for DNSStubListener=yes")
		}
	})

	t.Run("wrong section", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.conf")
		os.WriteFile(path, []byte("[Other]\nDNSStubListener=no\n"), 0644)

		if hasStubListenerDisabled(path) {
			t.Error("expected false for wrong section")
		}
	})

	t.Run("commented out", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.conf")
		os.WriteFile(path, []byte("[Resolve]\n#DNSStubListener=no\n"), 0644)

		if hasStubListenerDisabled(path) {
			t.Error("expected false for commented-out setting")
		}
	})

	t.Run("missing file", func(t *testing.T) {
		if hasStubListenerDisabled("/nonexistent/file.conf") {
			t.Error("expected false for missing file")
		}
	})

	t.Run("case insensitive value", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.conf")
		os.WriteFile(path, []byte("[Resolve]\nDNSStubListener=No\n"), 0644)

		if !hasStubListenerDisabled(path) {
			t.Error("expected true for case-insensitive No")
		}
	})

	t.Run("spaces around equals", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.conf")
		os.WriteFile(path, []byte("[Resolve]\nDNSStubListener = no\n"), 0644)

		if !hasStubListenerDisabled(path) {
			t.Error("expected true for spaced DNSStubListener = no")
		}
	})
}

func TestLinuxDNSChecks(t *testing.T) {
	checks := linuxDNSChecks()
	if len(checks) != 3 {
		t.Fatalf("expected 3 Linux DNS checks, got %d", len(checks))
	}

	expected := []struct {
		name     string
		category string
	}{
		{"resolv.conf routing", "DNS"},
		{"DNS stub listener", "DNS"},
		{"End-to-end DNS", "DNS"},
	}

	for i, want := range expected {
		if checks[i].Name != want.name {
			t.Errorf("check %d: name = %q, want %q", i, checks[i].Name, want.name)
		}
		if checks[i].Category != want.category {
			t.Errorf("check %d: category = %q, want %q", i, checks[i].Category, want.category)
		}
	}
}
